services:
  - type: web
    name: cooking-recipes-nutrition
    env: python
    buildCommand: "bash ./build.sh"
    startCommand: "gunicorn CookingRecipess.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
